# Generated by Django 2.2 on 2019-12-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191220_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='num_votes',
            field=models.IntegerField(default=0),
        ),
    ]
