# Generated by Django 2.2 on 2019-12-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20191222_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='notificate',
            new_name='notifications',
        ),
    ]
